name: Docs PR

on:
    pull_request_target:
        branches: [ '**' ]
        paths:
            - 'dokka/**'
            - 'src/main/**'
            - '.github/workflows/docs-pr.yml'

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: "${{ github.event.pull_request.merge_commit_sha }}"
                  fetch-depth: 0
            - uses: actions/setup-java@v4
              with:
                java-version: 21
                distribution: zulu
                cache: gradle
            -   name: Build docs
                run: ./gradlew --no-daemon dokkaHtml dokkaJavadoc
            - name: Copy javadoc subfolder
              run: mv build/dokka/javadoc build/dokka/html/ && cp dokka/includes/404.html build/dokka/html/
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: 'build/dokka/html'
            - uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
                  directory: build/dokka/html
                  branch: pr-${{ github.event.pull_request.number }}
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
